spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      location: ${java.io.tmpdir}
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/shop
  messages:
    basename: messages # default value
  mail:
    host: smtp.gmail.com
    port: 587
    username: xxx
    password: xxx
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  thymeleaf:
    enabled: false
apiPrefix: api
emailSender: shop@training.pl
availableLanguages: pl
defaultLanguage: pl